### ISSUE TITLE
(DBConnection.ConnectionError) connection not available and request was dropped from queue

### ISSUE THREAD

**Issue by zulhfreelancer** [zulhfreelancer/blockscout_explorer_docker#1]
We are getting a lot of these errors:

```
2019-07-16T07:14:46.240 [error] Task #PID<0.1534.0> started from Indexer.Block.Realtime.Fetcher terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1224ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
    (db_connection) lib/db_connection.ex:778: DBConnection.transaction/3
    (ecto) lib/ecto/repo/transaction.ex:16: Ecto.Repo.Transaction.transaction/3
    (stdlib) timer.erl:197: :timer.tc/3
    (explorer) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer) lib/explorer/chain/import.ex:316: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
    (elixir) lib/enum.ex:3317: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1990: Enum.reduce_while/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [321887, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://geth:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
```

**Comment by zulhfreelancer** [comment]
Hi @rjl493456442, I inspired by your work to include BlockScout natively in Geth 1.9 version. Here, I'm trying to come out with Docker Compose version of it for non-puppeth users. I wrote my motivation and plans [here](https://github.com/zulhfreelancer/blockscout_explorer_docker).

While building, I came across some errors and I couldn't figure out why. So, I would like to ask for your help to look at [issues](https://github.com/zulhfreelancer/blockscout_explorer_docker/issues) that I have here and provide me some inputs.

Really appreciate your help! 🙏🏼

Note: I'm a complete beginner to Elixir and Phoenix.

cc: @acravenho, @KronicDeth, @vbaranov

**Comment by rjl493456442** [comment]
@zulhfreelancer Hi nice work! I open a similar issue in the upstream repo. https://github.com/poanetwork/blockscout/issues/2308

@ayrat555 is active to help with the issue. You can try his latest fix.

**Comment by zulhfreelancer** [comment]
@rjl493456442 thank you. I'll check them out. Any inputs for other [issues](https://github.com/zulhfreelancer/blockscout_explorer_docker/issues)?
